metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "da54ee0ea5aefb5a0bfcced36c13e513725ee00b4e66172aff5acc40e561ba97"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".localhost"
index = "index.html"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "f92f887c02661c0aef4fcc1036552097ec2fa40a77fa7c33733cab6f4cf13bc8"
metrics_token = "43571c9093200dd55485eaa331998edbf4cfee832479fdfe7e4b738684b41b3b"
